/* RESETEAR SECUENCIA USUARIO*/ 
drop sequence "CONSULTORIA"."USUARIO_IDUSUARIO_SEQ";
CREATE SEQUENCE  "CONSULTORIA"."USUARIO_IDUSUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

/* USUARIOS */
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('admin1', 'admin', '123', 'admin1@consultoria.cl', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('admin2', 'admin', '123', 'admin2@consultoria.cl', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('cliente1', 'cliente', '123', 'cliente1@cliente1.com', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('cliente2', 'cliente', '123', 'cliente2@cliente2.com', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('cliente3', 'cliente', '123', 'cliente3@cliente3.com', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('cliente4', 'cliente', '123', 'cliente4@cliente4.com', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('prev1', 'profesional', '123', 'prev1@consultoria.cl', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('prev2', 'profesional', '123', 'prev2@consultoria.cl', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('prev3', 'profesional', '123', 'prev3@consultoria.cl', '1');
INSERT INTO "CONSULTORIA"."USUARIO" (USUARIO, TIPOUSUARIO, CLAVE, MAIL, ACTIVO) VALUES ('prev4', 'profesional', '123', 'prev4@consultoria.cl', '0');

/* USUARIO ADMIN */
INSERT INTO "CONSULTORIA"."ADMIN" (IDEMPLEADO, NOMBRE, USUARIO_IDUSUARIO) VALUES ('1', 'Juan Administrador', '1');
INSERT INTO "CONSULTORIA"."ADMIN" (IDEMPLEADO, NOMBRE, USUARIO_IDUSUARIO) VALUES ('2', 'Perla Administradora', '2');


/* USUARIO PROFESIONAL */
INSERT INTO "CONSULTORIA"."PROFESIONAL" (IDEMPLEADO, NOMBRE, USUARIO_IDUSUARIO, CELULAR) VALUES ('3', 'Amanda Prevencionista', '7', '+56912340001');
INSERT INTO "CONSULTORIA"."PROFESIONAL" (IDEMPLEADO, NOMBRE, USUARIO_IDUSUARIO, CELULAR) VALUES ('4', 'Braulio  Prevencionista', '8', '+56912340002');
INSERT INTO "CONSULTORIA"."PROFESIONAL" (IDEMPLEADO, NOMBRE, USUARIO_IDUSUARIO, CELULAR) VALUES ('5', 'Catalina  Prevencionista', '9', '+56912340003');
INSERT INTO "CONSULTORIA"."PROFESIONAL" (IDEMPLEADO, NOMBRE, USUARIO_IDUSUARIO, CELULAR) VALUES ('6', 'Danilo  Prevencionista', '10', '+56912340004');


/* RESETEAR SECUENCIA CLIENTE*/ 
drop sequence "CONSULTORIA"."CLIENTE_IDCLIENTE_SEQ";
CREATE SEQUENCE  "CONSULTORIA"."CLIENTE_IDCLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

/* USUARIO CLIENTE */
INSERT INTO "CONSULTORIA"."CLIENTE" (NOMBREEMPRESA, RUTEMPRESA, USUARIO_IDUSUARIO) VALUES ('Empresa Amarillo', '76000001', '3');
INSERT INTO "CONSULTORIA"."CLIENTE" (NOMBREEMPRESA, RUTEMPRESA, USUARIO_IDUSUARIO) VALUES ('Empresa Blanco', '76000002', '4');
INSERT INTO "CONSULTORIA"."CLIENTE" (NOMBREEMPRESA, RUTEMPRESA, USUARIO_IDUSUARIO) VALUES ('Empresa Calipso', '76000003', '5');
INSERT INTO "CONSULTORIA"."CLIENTE" (NOMBREEMPRESA, RUTEMPRESA, USUARIO_IDUSUARIO) VALUES ('Empresa Dorado', '76000004', '6');
