/* SOLICITUDES ASESORIA */
INSERT INTO "CONSULTORIA"."SOLICITUDASESORIA" (FECHAHORA, MOTIVO, PREFERENCIAHORARIO, CLIENTE_IDCLIENTE) VALUES (TO_DATE('2020-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Preparación para auditoria', 'mañana', '1');
INSERT INTO "CONSULTORIA"."SOLICITUDASESORIA" (FECHAHORA, MOTIVO, PREFERENCIAHORARIO, CLIENTE_IDCLIENTE) VALUES (TO_DATE('2020-07-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Implementación plan de seguridad en faena', 'tarde', '2');
INSERT INTO "CONSULTORIA"."SOLICITUDASESORIA" (FECHAHORA, MOTIVO, PREFERENCIAHORARIO, CLIENTE_IDCLIENTE) VALUES (TO_DATE('2020-07-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Revisar accidentabilidad 2020', 'mañana', '3');
INSERT INTO "CONSULTORIA"."SOLICITUDASESORIA" (FECHAHORA, MOTIVO, PREFERENCIAHORARIO, CLIENTE_IDCLIENTE) VALUES (TO_DATE('2020-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Asesoria para implementacion de comité paritario', 'tarde', '4');
