/*ACTIVIDADES DE MEJORA */
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Comité Paritario', 'Creación de comité paritario de higiene y seguridad', TO_DATE('2020-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Realizado', 'Comité creado exitosamente. Se cuentan 200 votos', '1');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Comité Paritario', 'Creación de comité paritario de higiene y seguridad', TO_DATE('2020-06-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Realizado', 'Comité creado exitosamente. Se cuentan 157 votos', '2');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Comité Paritario', 'Creación de comité paritario de higiene y seguridad', TO_DATE('2020-08-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 'Votacion agendada para ultima semana julio', '3');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Comité Paritario', 'Creación de comité paritario de higiene y seguridad', TO_DATE('2020-10-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 'No se registran avances', '4');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Señaletica', 'Renovar señaletica en pasillos de la bodega', TO_DATE('2020-12-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 'No se registran avances', '1');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Capacitación Seguridad', 'Realizar capacitación en seguridad de operaciones a equipos de faena', TO_DATE('2020-11-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 'No se registran avances', '2');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Derecho a Saber', 'Implementar proceso de capacitación Derecho a Saber para trabajadores nuevos', TO_DATE('2020-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Realizado', 'Implementado exitosamente', '3');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Vacunas', 'Implementar operativo de vacunacion influenza', TO_DATE('2020-03-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Realizado', 'Realizado exitosamente', '4');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Elementos Proteccion Personal', 'Comprar cascos y guantes clase 1 para operadores de maquinaria', TO_DATE('2020-10-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 'No se registran avances', '1');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Capacitación emergencias', 'Realizar capacitación a equipo en contención de emergencias', TO_DATE('2020-09-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 'No se registran avances', '2');
INSERT INTO "CONSULTORIA"."ACTIVIDAD" (TITULO, DESCRIPCION, FECHAPLAZO, STATUS, COMENTARIO, CLIENTE_IDCLIENTE) VALUES ('Mantención maquinas', 'Realizar mantención de maquinaria de envasado', TO_DATE('2020-10-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente', 'No se registran avances', '3');
