
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('1', '1', 'Derecho a Saber', 'Informar a sus colaboradores sobre los peligros y riesgos que están presentes en sus labores', '* Introduccion *Riesgos *Desarrollo * Preguntas *Cierre', 'Sala, Computador, Notebook', TO_DATE('2020-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '7');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('2', '2', 'Derecho a Saber', 'Informar a sus colaboradores sobre los peligros y riesgos que están presentes en sus labores', '* Introduccion *Riesgos *Desarrollo * Preguntas *Cierre', 'Sala, Computador, Notebook', TO_DATE('2020-06-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '8');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('3', '3', 'Derecho a Saber', 'Informar a sus colaboradores sobre los peligros y riesgos que están presentes en sus labores', '* Introduccion *Riesgos *Desarrollo * Preguntas *Cierre', 'Sala, Computador, Notebook', TO_DATE('2020-08-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '9');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('4', '4', 'Derecho a Saber', 'Informar a sus colaboradores sobre los peligros y riesgos que están presentes en sus labores', '* Introduccion *Riesgos *Desarrollo * Preguntas *Cierre', 'Sala, Computador, Notebook', TO_DATE('2020-10-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '10');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('1', '5', 'Operación maquina t-1000', 'Lograr las habilidades para la operación eficiente y segura de la maquina t-1000', '*Introduccion *Encendido *Operación * Mantencion * Apagado', 'Sala, T-1000, repuestos', TO_DATE('2020-12-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '7');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('2', '6', 'Procedimiento empaquetado', 'Conocer las normas de seguridad del procedimiento de  empaquetado', '* Introduccion *Etapa 1 *Etapa2 * Etapa3 *Cierre', 'Sala, Computador, Notebook', TO_DATE('2020-11-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '8');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('3', '7', 'Procedimiento emergencias', 'Conocer los procedimientos que deben efectuar los equipos de seguridad en situaciones de emergencia', '*Introduccion *Caso de incendio *Terremoto *Terrorismo *Cierre', 'Sala, Computador, Notebook', TO_DATE('2020-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '9');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('4', '8', 'Primeros Auxilios', 'Dominar las tecnicas de primeros auxilios', '*Introduccion * CPR * Entablillado *Cierre', 'Muñeco, Sala, Computador, Notebook', TO_DATE('2020-03-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '10');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('1', '9', 'Primeros Auxilios', 'Dominar las tecnicas de primeros auxilios', '*Introduccion * CPR * Entablillado *Cierre', 'Muñeco, Sala, Computador, Notebook', TO_DATE('2020-10-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '7');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('2', '10', 'Uso de extintores', 'Uso adecuado de extintores portátiles', '*Introduccion *Quimica *El extintor *Proteccion personal', 'Simulador de extintores', TO_DATE('2020-09-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '8');
INSERT INTO "CONSULTORIA"."CAPACITACION" (CLIENTE_IDCLIENTE, IDCAPACITACION, TEMA, OBJETIVOS, CONTENIDOS, RECURSOS, FECHA, IDUSUARIOPRO) VALUES ('3', '11', 'Uso de extintores', 'Uso adecuado de extintores portátiles', '*Introduccion *Quimica *El extintor *Proteccion personal', 'Simulador de extintores', TO_DATE('2020-10-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '9');